### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by TheMysterys** [dries007/MCLink_Mod#21]
It works for if someone's account is linked but otherwise just throws this error. API key is still valid as I went and checked it before creating this. (Server version Paper 1.14.4 (243))

```
[12:02:26 ERROR]: [MCLink] Caught error:
APIException: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.

net.dries007.mclink.api.APIException: The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.
        at net.dries007.mclink.api.API.parseConnectionOutput(API.java:296) ~[?:?]
        at net.dries007.mclink.api.API.doPostRequest(API.java:340) ~[?:?]
        at net.dries007.mclink.api.API.doPostRequest(API.java:310) ~[?:?]
        at net.dries007.mclink.api.API.getAuthorization(API.java:238) ~[?:?]
        at net.dries007.mclink.api.API.getAuthorization(API.java:198) ~[?:?]
        at net.dries007.mclink.common.MCLinkCommon.check(MCLinkCommon.java:259) ~[?:?]
        at net.dries007.mclink.common.MCLinkCommon.lambda$checkAuthStatusAsync$5(MCLinkCommon.java:249) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-243]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-243]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by dries007** [comment]
Does this still happen? I fixed some other issues in the meantime and I think this might have been fixed in the meantime. Sorry for the late reply.
